apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kairyu.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "kairyu.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "kairyu.fullname" . }}
    spec:
      containers:
        - name: kairyu
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
          volumeMounts:
            - name: config
              mountPath: /etc/kairyu
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "kairyu.fullname" . }}-config
