FROM mcr.microsoft.com/playwright:v1.60.0-noble@sha256:83192064c7510f7ee73dd63dc5f22a5e01a92c81a2e6a9c715d9e3fe55471fd9

WORKDIR /work
COPY deploy/compose/webui-browser/package.json \
     deploy/compose/webui-browser/package-lock.json ./
RUN npm ci --omit=dev --ignore-scripts \
    && npm cache clean --force
